language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - npm start

after_script:
  - git init
  - git config user.name "liuxiaoming"
  - git config user.email "liuxiaoming8841@gmail.com"
  - git add .
  - git commit -m "Update subscribe"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

# branches:
#   only:
#     - blog-source
env:
 global:
   - GH_REF: github.com/happier2/ssr-subscribe.git