language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - npm start

after_success:
  - git init
  - git config user.name "happier2"
  - git config user.email "13118619+happier2@users.noreply.github.com"
  - git add .
  - git commit -m "Update subscribe by Travis"
  - git push --force "https://happier2:${GH_TOKEN}@${GH_REF}"
# E: Build LifeCycle

# branches:
#   only:
#     - blog-source
env:
 global:
   - GH_REF: github.com/happier2/ssr-subscribe.git